### ISSUE TITLE
[Bug]: Pressing escape jumps to other tab

### ISSUE THREAD

**Issue by mvdssel** [Quorafind/Obsidian-Daily-Notes-Editor#73]
### Bug Description

When multiple tabs are open, pressing escape will always move the active tab away from daily notes. This makes the daily notes plugin unusable when using vim mode in Obsidian. Is it possible to disable this behavior by default when Vim mode is enabled in Obsidian? 

### To Reproduce

1. have VIM mode enabled
2. have more than 1 tab open
3. have the daily notes as active tab
4. as soon as escape is pressed, the active tab switches to something else than daily notes. 

### Obsidian Version

1.9.12

### Which plugin are you using for daily notes?

- [x] Default Daily Note Plugin
- [x] Periodic Notes Plugin

### Checklist

- [x] I updated to the latest version of the plugin.

**Comment by e-zz** [comment]
Same here. 
Very annoying for vim keybinding users.

---

I just noticed there used to be some discussions on it https://github.com/Quorafind/Obsidian-Daily-Notes-Editor/issues/46
And it's seemingly been fixed in https://github.com/Cyberdr8gon/Obsidian-Daily-Notes-Editor/commit/120484fa283f6e57215545b445cee1b724393b03

One thing very confusing to me is that, to enable this fix, one has to turn on the plugin option `Use arrow up/down key to navigate between notes`


---

Update:
I build the plugin myself and with the plugin option `Use arrow up/down key to navigate between notes`, I get rid of the problem.
But with the official version, this workaround fails somehow.

**Comment by tdelanversin** [comment]
Same here, I still experience it with the latest version on MacOS

**Comment by tdelanversin** [comment]
> Update: I build the plugin myself and with the plugin option `Use arrow up/down key to navigate between notes`, I get rid of the problem. But with the official version, this workaround fails somehow.

@e-zz how did you build it yourself? I'm having trouble with npm install (I'm also not well versed in npm)
